env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - prettier
  - plugin:perfectionist/recommended-natural
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - prettier
  - "@typescript-eslint"
  - vue
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
      bracketSpacing: true
      arrowParens: avoid
      max-len:
        - error
        - 140
        - 2
      tabWidth: 4
      useTabs: false
      semi: true
  indent:
    - error
    - 4
    - SwitchCase: 1
  vue/multi-word-component-names: 0
  "@typescript-eslint/no-explicit-any": 0
  vue/no-v-html: 0
  vue/require-explicit-emits: 0
  perfectionist/sort-vue-attributes: 0
  perfectionist/sort-objects: 0
